// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjcTnjWMyY6zh_iQLdbs9qBr1kkmamWmU',
    appId: '1:477752467975:web:7a858933387ab3438980a2',
    messagingSenderId: '477752467975',
    projectId: 'that-girl-tracker',
    authDomain: 'that-girl-tracker.firebaseapp.com',
    storageBucket: 'that-girl-tracker.firebasestorage.app',
    measurementId: 'G-H5Z1STCQRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4VtFm48hLU5tbZJptvYvgZdx7ZTxI0Y',
    appId: '1:477752467975:android:406201934585a56f8980a2',
    messagingSenderId: '477752467975',
    projectId: 'that-girl-tracker',
    storageBucket: 'that-girl-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOvQ5n6cp4Lw1agZKe9UvR6UdUO7oQ0g',
    appId: '1:477752467975:ios:82cb81bcacea7aed8980a2',
    messagingSenderId: '477752467975',
    projectId: 'that-girl-tracker',
    storageBucket: 'that-girl-tracker.firebasestorage.app',
    iosBundleId: 'com.kikis.thatGirlTracker',
  );
}
